# Generated by Django 4.2 on 2023-04-08 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studio',
            name='logo',
            field=models.ImageField(null=True, upload_to='studio_logos'),
        ),
    ]
