# Generated by Django 4.2 on 2023-05-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0003_alter_studio_founded_alter_studio_founder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studio',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
    ]
