# Generated by Django 4.2 on 2023-04-08 09:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('studio', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('style', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('release_date', models.DateField()),
                ('publisher', models.CharField(max_length=100)),
                ('rating_metacritic', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('rating_ign', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('engine', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=2, validators=[django.core.validators.MinValueValidator(0.0)])),
            ],
        ),
    ]
