# Generated by Django 4.2 on 2023-05-27 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0012_alter_game_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('rating', models.IntegerField(choices=[(1, 0), (2, 1), (3, 2), (4, 3), (5, 4), (6, 5)], verbose_name='Рейтинг')),
                ('comment', models.TextField(verbose_name='Ревью')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game', verbose_name='Игра')),
            ],
        ),
    ]
