# Generated by Django 4.2 on 2023-05-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishers', '0002_alter_publisher_desc_alter_publisher_founded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
    ]
